//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Channels = new HashSet<Channel>();
            this.Messages = new HashSet<Message>();
            this.Chats = new HashSet<Chat>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string SessionKey { get; set; }
    
        public virtual ICollection<Channel> Channels { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Chat> Chats { get; set; }
    }
}
